<?php
/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 */
 // Add Macland Options to Admin Menu.
 $pages = array(
   'maxwell_options'   => array(
     'page_title'    => __( 'Maxwell Options', 'devdmbootstrap3' ),
     'position'      => 4,
     'sections'      => array(
       'section-one'   => array(
         'title'         => __( 'Layout Options', 'devdmbootstrap3' ),
         'fields'        => array(
           'fluid_container' => array(
             'title'         => __( 'Use Fluid Containers', 'devdmbootstrap3' ),
             'id'            => 'fluid_container',
             'type'          => 'checkbox',
             'text'          => __( 'Check to use full-width fluid containers on pages.', 'devdmbootstrap3' ),
           ),
           'header_container' => array(
             'title'         => __( 'Header in main container', 'devdmbootstrap3' ),
             'id'            => 'header_container',
             'type'          => 'checkbox',
             'text'          => __( 'Check to put header in the main container on pages.', 'devdmbootstrap3' ),
           ),
           'footer_container' => array(
             'title'         => __( 'Footer in main container', 'devdmbootstrap3' ),
             'id'            => 'footer_container',
             'type'          => 'checkbox',
             'text'          => __( 'Check to put footer in the main container on pages.', 'devdmbootstrap3' ),
           ),
           'complex_header'  => array(
             'title'         => __( 'Display Complex Header' ),
             'id'            => 'complex_header',
             'type'          => 'checkbox',
             'text'          => __( 'Display Complex Header with Header Image and Menu in the same row. This will bypass the DmSettings Display Header.' ),
           ),
           'radio'           => array(
             'title'         => __( 'Navbar Style', 'devdmbootstrap3' ),
             'id'            => 'navebar_style',
             'type'          => 'radio',
             'choices'       => array(
               'default'    => __( 'Default style, light gray', 'devdmbootstrap3' ),
               'inverse'    => __( 'Inverse style, almost black', 'devdmbootstrap3' ),
               'custom'     => __( 'Customed style, can be customed', 'devdmbootstrap3' ),
             ),
           ),
           'menu_search'    => array(
             'title'         => __( 'Display Search on Main Menu' ),
             'id'            => 'menu_search',
             'type'          => 'checkbox',
             'text'          => __( 'Display Search on Main Menu. If thrid party menu search plugin installed, uncheck this' ),
           ),
         ),
       ),
//       'section-two'   => array(
//         'title'         => __( 'Homepage Options', 'devdmbootstrap3' ),
//         'fields'        => array(
//           'act_pic'         => array(
//             'title'         => __( 'Activity Picture' ),
//             'id'            => 'activity_pic',
//             'type'          => 'media',
//             'value'         => '',
//             'placeholder'   => 'Click Upload to upload or choose picture for Activity',
//           ),
//           'act_date'        => array(
//             'title'         => __( 'Activity Date' ),
//             'id'            => 'activity_date',
//             'type'          => 'date',
//             'value'         => 'now',
//           ),
//           'h_slider_1'      => array(
//             'title'         => __( 'Home Slider Picrure 1' ),
//             'id'            => 'home_slider_1',
//             'type'          => 'media',
//             'value'         => '',
//             'placeholder'   => 'Click Upload to upload or choose the picture.',
//           ),
//           'h_sl_link_1'     => array(
//             'title'         => __( 'Home Slider Link 1' ),
//             'id'            => 'home_slider_link_1',
//             'type'          => 'url',
//             'placeholder'   => 'Link for Home Slider 1',
//           ),
//           'h_slider_2'      => array(
//             'title'         => __( 'Home Slider Picrure 2' ),
//             'id'            => 'home_slider_2',
//             'type'          => 'media',
//             'value'         => '',
//             'placeholder'   => 'Click Upload to upload or choose the picture.',
//           ),
//           'h_sl_link_2'     => array(
//             'title'         => __( 'Home Slider Link 2' ),
//             'id'            => 'home_slider_link_2',
//             'type'          => 'url',
//             'placeholder'   => 'Link for Home Slider 2',
//           ),
//           'h_slider_3'      => array(
//             'title'         => __( 'Home Slider Picrure 3' ),
//             'id'            => 'home_slider_3',
//             'type'          => 'media',
//             'value'         => '',
//             'placeholder'   => 'Click Upload to upload or choose the picture.',
//           ),
//           'h_sl_link_3'     => array(
//             'title'         => __( 'Home Slider Link 3' ),
//             'id'            => 'home_slider_link_3',
//             'type'          => 'url',
//             'placeholder'   => 'Link for Home Slider 3',
//           ),
//           'disp_contact'    => array(
//             'title'         => __( 'Staff Contact Information' ),
//             'id'            => 'display_contact',
//             'type'          => 'checkbox',
//             'text'          => __( 'Display contact information in Team Page' ),
//           ),
//         ),
//       ),
       'section-three'   => array(
         'title'         => __( 'Business Options', 'devdmbootstrap3' ),
         'fields'        => array(
           'comp_tel'        => array(
             'title'         => __( 'Company Telephone', 'devdmbootstrap3' ),
             'id'            => 'company_tel',
             'type'          => 'tel',
             'placeholder'   => '61-412-901-396',
           ),
           'comp_fax'        => array(
             'title'         => __( 'Company Fax' ),
             'id'            => 'company_fax',
             'type'          => 'tel',
             'placeholder'   => '61-2-9736-2681',
           ),
           'comp_email'        => array(
             'title'         => __( 'Company Telephone', 'devdmbootstrap3' ),
             'id'            => 'company_email',
             'type'          => 'email',
             'placeholder'   => 'enquiry@maxwellit.com.au',
           ),
           'comp_address'    => array(
             'title'         => __( 'Company Address', 'devdmbootstrap3' ),
             'id'            => 'company_address',
             'type'          => 'text',
             'placeholder'   => '32/29-31 Paul St Bondi Junction NSW 2022',
           ),
           'comp_s_weibo'    => array(
             'title'         => __( 'Sina Weibo', 'devdmbootstrap3' ),
             'id'            => 'company_sina_weibo',
             'type'          => 'url',
             'placeholder'   => __( 'Link of Sina Weibo', 'devdmbootstrap3' ),
           ),
           'comp_t_weibo'    => array(
             'title'         => __( 'Tencent Weibo', 'devdmbootstrap3' ),
             'id'            => 'company_tencent_weibo',
             'type'          => 'url',
             'placeholder'   => __( 'Link of Tencent Weibo', 'devdmbootstrap3' ),
           ),
           'comp_facebook'   => array(
             'title'         => __( 'Facebook', 'devdmbootstrap3' ),
             'id'            => 'company_facebook',
             'type'          => 'url',
             'placeholder'   => __( 'Link of Facebook', 'devdmbootstrap3' ),
           ),
           'comp_twitter'    => array(
             'title'         => __( 'Twitter', 'devdmbootstrap3' ),
             'id'            => 'company_twitter',
             'type'          => 'url',
             'placeholder'   => __( 'Link of Twitter', 'devdmbootstrap3' ),
           ),
           'comp_linkedin'     => array(
             'title'         => __( 'Linkedin', 'devdmbootstrap3' ),
             'id'            => 'company_linkedin',
             'type'          => 'url',
             'placeholder'   => __( 'Link of Linkedin', 'devdmbootstrap3' ),
           ),
           'comp_wechat'     => array(
             'title'         => __( 'WeChat QrCode' ),
             'id'            => 'company_wechat',
             'type'          => 'media',
             'value'         => '',
             'placeholder'   => __( 'Click Upload to upload or choose the QrCode.', 'devdmbootstrap3' ),
           ),
         ),
       ),
     ),
   ),
 );
 $option_page = new RationalOptionPages( $pages );
?>
