<?php
/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 */
// Register Custom Post Type: Partner
if ( ! function_exists('custom_post_type_partner') ) {
function custom_post_type_partner() {
	$labels = array(
		'name'                  => _x( 'Partners', 'Post Type General Name', 'devdmbootstrap3' ),
		'singular_name'         => _x( 'Partner', 'Post Type Singular Name', 'devdmbootstrap3' ),
		'menu_name'             => __( 'Partners', 'devdmbootstrap3' ),
		'name_admin_bar'        => __( 'Partner', 'devdmbootstrap3' ),
		'archives'              => __( 'Partner Archives', 'devdmbootstrap3' ),
		'parent_item_colon'     => __( 'Parent Partner:', 'devdmbootstrap3' ),
		'all_items'             => __( 'All Partners', 'devdmbootstrap3' ),
		'add_new_item'          => __( 'Add New Partner', 'devdmbootstrap3' ),
		'add_new'               => __( 'Add New', 'devdmbootstrap3' ),
		'new_item'              => __( 'New Partner', 'devdmbootstrap3' ),
		'edit_item'             => __( 'Edit Partner', 'devdmbootstrap3' ),
		'update_item'           => __( 'Update Partner', 'devdmbootstrap3' ),
		'view_item'             => __( 'View Partner', 'devdmbootstrap3' ),
		'search_items'          => __( 'Search Partner', 'devdmbootstrap3' ),
		'not_found'             => __( 'Not found', 'devdmbootstrap3' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'devdmbootstrap3' ),
		'featured_image'        => __( 'Partner Logo', 'devdmbootstrap3' ),
		'set_featured_image'    => __( 'Set partner logo', 'devdmbootstrap3' ),
		'remove_featured_image' => __( 'Remove partner logo', 'devdmbootstrap3' ),
		'use_featured_image'    => __( 'Use as partner logo', 'devdmbootstrap3' ),
		'insert_into_item'      => __( 'Insert into partner', 'devdmbootstrap3' ),
		'uploaded_to_this_item' => __( 'Uploaded to this partner', 'devdmbootstrap3' ),
		'items_list'            => __( 'Partners list', 'devdmbootstrap3' ),
		'items_list_navigation' => __( 'Partners list navigation', 'devdmbootstrap3' ),
		'filter_items_list'     => __( 'Filter partners list', 'devdmbootstrap3' ),
	);
	$args = array(
		'label'                 => __( 'Partner', 'devdmbootstrap3' ),
		'description'           => __( 'Partner posts', 'devdmbootstrap3' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'thumbnail', ),
		'public'                => true,
		'has_archive'           => true,
		'menu_position'         => 0,
		'menu_icon'             => 'dashicons-groups',
		'can_export'            => true,
		'rewrite'               => array('slug' => 'partner'),
	);
	register_post_type( 'partner', $args );
}
add_action( 'init', 'custom_post_type_partner', 0 );
}

// Register Custom Post Type: Staff
if ( ! function_exists('custom_post_type_staff') ) {
function custom_post_type_staff() {
	$labels = array(
		'name'                  => _x( 'Staffs', 'Post Type General Name', 'devdmbootstrap3' ),
		'singular_name'         => _x( 'Staff', 'Post Type Singular Name', 'devdmbootstrap3' ),
		'menu_name'             => __( 'Staffs', 'devdmbootstrap3' ),
		'name_admin_bar'        => __( 'Staff', 'devdmbootstrap3' ),
		'archives'              => __( 'Staff Archives', 'devdmbootstrap3' ),
		'parent_item_colon'     => __( 'Parent Staff:', 'devdmbootstrap3' ),
		'all_items'             => __( 'All Staffs', 'devdmbootstrap3' ),
		'add_new_item'          => __( 'Add New Staff', 'devdmbootstrap3' ),
		'add_new'               => __( 'Add New', 'devdmbootstrap3' ),
		'new_item'              => __( 'New Staff', 'devdmbootstrap3' ),
		'edit_item'             => __( 'Edit Staff', 'devdmbootstrap3' ),
		'update_item'           => __( 'Update Staff', 'devdmbootstrap3' ),
		'view_item'             => __( 'View Staff', 'devdmbootstrap3' ),
		'search_items'          => __( 'Search Staff', 'devdmbootstrap3' ),
		'not_found'             => __( 'Not found', 'devdmbootstrap3' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'devdmbootstrap3' ),
		'featured_image'        => __( 'Staff photo', 'devdmbootstrap3' ),
		'set_featured_image'    => __( 'Set staff photo', 'devdmbootstrap3' ),
		'remove_featured_image' => __( 'Remove staff photo', 'devdmbootstrap3' ),
		'use_featured_image'    => __( 'Use as staff photo', 'devdmbootstrap3' ),
		'insert_into_item'      => __( 'Insert into staff', 'devdmbootstrap3' ),
		'uploaded_to_this_item' => __( 'Uploaded to this staff', 'devdmbootstrap3' ),
		'items_list'            => __( 'Staffs list', 'devdmbootstrap3' ),
		'items_list_navigation' => __( 'Staffs list navigation', 'devdmbootstrap3' ),
		'filter_items_list'     => __( 'Filter staffs list', 'devdmbootstrap3' ),
	);
	$args = array(
		'label'                 => __( 'Staff', 'devdmbootstrap3' ),
		'description'           => __( 'Staff pages', 'devdmbootstrap3' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'thumbnail', ),
		'public'                => true,
		'menu_position'         => 0,
		'menu_icon'             => 'dashicons-businessman',
		'can_export'            => true,
		'has_archive'           => true,
		'rewrite'               => array('slug' => 'staff'),

	);
	register_post_type( 'staff', $args );
}
add_action( 'init', 'custom_post_type_staff', 0 );
}

// Register Custom Taxonomy: Team
if ( ! function_exists( 'custom_taxonomy_team' ) ) {
function custom_taxonomy_team() {
	$labels = array(
		'name'                       => _x( 'Team', 'Taxonomy General Name', 'devdmbootstrap3' ),
		'singular_name'              => _x( 'Team', 'Taxonomy Singular Name', 'devdmbootstrap3' ),
		'menu_name'                  => __( 'Teams', 'devdmbootstrap3' ),
		'all_items'                  => __( 'All Teams', 'devdmbootstrap3' ),
		'parent_item'                => __( 'Parent Team', 'devdmbootstrap3' ),
		'parent_item_colon'          => __( 'Parent Team:', 'devdmbootstrap3' ),
		'new_item_name'              => __( 'New Team Name', 'devdmbootstrap3' ),
		'add_new_item'               => __( 'Add New Team', 'devdmbootstrap3' ),
		'edit_item'                  => __( 'Edit Team', 'devdmbootstrap3' ),
		'update_item'                => __( 'Update Team', 'devdmbootstrap3' ),
		'view_item'                  => __( 'View Team', 'devdmbootstrap3' ),
		'separate_items_with_commas' => __( 'Separate teams with commas', 'devdmbootstrap3' ),
		'add_or_remove_items'        => __( 'Add or remove teams', 'devdmbootstrap3' ),
		'choose_from_most_used'      => __( 'Choose from the most used', 'devdmbootstrap3' ),
		'popular_items'              => __( 'Popular Teams', 'devdmbootstrap3' ),
		'search_items'               => __( 'Search Teams', 'devdmbootstrap3' ),
		'not_found'                  => __( 'Not Found', 'devdmbootstrap3' ),
		'no_terms'                   => __( 'No teams', 'devdmbootstrap3' ),
		'items_list'                 => __( 'Teams list', 'devdmbootstrap3' ),
		'items_list_navigation'      => __( 'Teams list navigation', 'devdmbootstrap3' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => true,
		'query_var'                  => true,
		'rewrite'                    => true,
	);
	register_taxonomy( 'team', array( 'staff' ), $args );
}
add_action( 'init', 'custom_taxonomy_team', 0 );
}
?>
